import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import Footer from "@/components/Footer";
import QueryProvider from "./provider/QueryProvider";
import { NextProvider } from "./provider/NextUIProvider";
import Navbar from "@/components/Navbar";
import { serverSupabase } from "@/utils/supabase/server";
import { User } from "@supabase/supabase-js";
import {
  HydrationBoundary,
  QueryClient,
  dehydrate,
} from "@tanstack/react-query";
import { USER_DATA_QUERY_KEY } from "@/query/user/userQueryKey";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });
const sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const setUser = async () => {
    const supabase = serverSupabase();
    const {
      data: { user },
      error,
    } = await supabase.auth.getUser();
    if (!user || error) throw error;
    const { data: userData, error: userDataErr } = await supabase
      .from("users")
      .select("*")
      .eq("user_id", String((user as User).id))
      .single();
    if (!userData || userDataErr) {
      console.log(userDataErr.message);
    } else {
      return userData;
    }
  };
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery({
    queryKey: [USER_DATA_QUERY_KEY],
    queryFn: setUser,
  });
  return (
    <html lang="en" className={sans.className}>
      <body className={inter.className}>
        <NextProvider>
          <QueryProvider>
            <HydrationBoundary state={dehydrate(queryClient)}>
              <Suspense>
                <Navbar />
                {children}
                <Footer />
              </Suspense>
            </HydrationBoundary>
          </QueryProvider>
        </NextProvider>
      </body>
    </html>
  );
}
